// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-MZqlOds9BoFLW49JByFZwCrzOqGeIjI',
    appId: '1:349087616804:web:995045415a6c2332c62db1',
    messagingSenderId: '349087616804',
    projectId: 'capmatch-646e7',
    authDomain: 'capmatch-646e7.firebaseapp.com',
    storageBucket: 'capmatch-646e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq7ulCX_Mk-7vkbLqqkkM1EUwE8ntlPXY',
    appId: '1:349087616804:android:a591d60edd4fed19c62db1',
    messagingSenderId: '349087616804',
    projectId: 'capmatch-646e7',
    storageBucket: 'capmatch-646e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA42LwCKiJ6RpMF9N-M2h_EMzItXquL_Yk',
    appId: '1:349087616804:ios:a9e3cb247a921b2fc62db1',
    messagingSenderId: '349087616804',
    projectId: 'capmatch-646e7',
    storageBucket: 'capmatch-646e7.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA42LwCKiJ6RpMF9N-M2h_EMzItXquL_Yk',
    appId: '1:349087616804:ios:a9e3cb247a921b2fc62db1',
    messagingSenderId: '349087616804',
    projectId: 'capmatch-646e7',
    storageBucket: 'capmatch-646e7.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-MZqlOds9BoFLW49JByFZwCrzOqGeIjI',
    appId: '1:349087616804:web:e82f39f50c3a3646c62db1',
    messagingSenderId: '349087616804',
    projectId: 'capmatch-646e7',
    authDomain: 'capmatch-646e7.firebaseapp.com',
    storageBucket: 'capmatch-646e7.firebasestorage.app',
  );
}
